apiVersion: apps/v2
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 3
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
        - name: conversao-temperatura
          image: giancarloh/conversao-temperatura:v2
---
apiVersion: v2
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001